language: python
sudo: false
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install coveralls
script:
  - nosetests -v --with-coverage --cover-erase --cover-package=ashaw_notes
after_success:
  - coveralls