language: python
sudo: false
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
script:
- nosetests -v --with-coverage --cover-erase --cover-package=utils,connectors,quicknote